version: '3.8'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    container_name: nats-server

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_user
    container_name: postgres-auth

  postgres-store:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_stores
    container_name: postgres-store  